name: Docker registry

on: 
   push:
     tags:
       - 'v*'

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build :tag
        if: success()
        run: |  
          repo_name=$(cut -f 2 -d "/" <(echo ${{ github.repository }}))
          docker build -t zavolab/${repo_name}:latest .
          docker tag zavolab/${repo_name}:latest zavolab/${repo_name}:${IMAGE_TAG} 
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push zavolab/${repo_name}:latest
          docker push zavolab/${repo_name}:${IMAGE_TAG}
