name: Docker registry

on: 
   push:
     tags:
       - 'v*'

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        if: success()
        env: 
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
        run: |  
          repo_name=$(cut -f 2 -d "/" <(echo ${{ github.repository }}))
          #docker build -t zavolab/${repo_name}:latest .
          #docker tag zavolab/${repo_name}:latest zavolab/${repo_name}:${IMAGE_TAG} 
          echo $docker_password | docker login -u $docker_username --password-stdin
          #docker push zavolab/${repo_name}:latest
          #docker push zavolab/${repo_name}:${IMAGE_TAG}
